services:
  ffgo-watch:
    build:
      context: # Path to git directory
      dockerfile: # Path to Dockerfile in git directory
    image: ffgo:local
    container_name: ffgo-watch
    restart: unless-stopped
    command: 
      - "ffgo"
      - "--jobs"
      - "2"
      - "watch"
      - "/transcodes/"
    volumes:
      # Update volumes to reflect your input/output directories.
      # Note: output directory in job.toml must use the volume's file system path.
      - /docker/ffgo/transcodes:/transcodes
      - /docker/ffgo/output:/output